# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pet_adoption.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pet_adoption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pet_adoption.proto\x12\x0cpet_adoption\"P\n\x03Pet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\r\n\x05\x62reed\x18\x04 \x01(\t\x12\x0f\n\x07picture\x18\x05 \x01(\t\"_\n\x12RegisterPetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\r\n\x05\x62reed\x18\x04 \x01(\t\x12\x0f\n\x07picture\x18\x05 \x01(\t\"&\n\x13RegisterPetResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"L\n\x10SearchPetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06gender\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\r\n\x05\x62reed\x18\x04 \x01(\t\"4\n\x11SearchPetResponse\x12\x1f\n\x04pets\x18\x01 \x03(\x0b\x32\x11.pet_adoption.Pet2\xb6\x01\n\x12PetAdoptionService\x12R\n\x0bRegisterPet\x12 .pet_adoption.RegisterPetRequest\x1a!.pet_adoption.RegisterPetResponse\x12L\n\tSearchPet\x12\x1e.pet_adoption.SearchPetRequest\x1a\x1f.pet_adoption.SearchPetResponseB\x0fZ\rpet_adoption/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pet_adoption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rpet_adoption/'
  _globals['_PET']._serialized_start=36
  _globals['_PET']._serialized_end=116
  _globals['_REGISTERPETREQUEST']._serialized_start=118
  _globals['_REGISTERPETREQUEST']._serialized_end=213
  _globals['_REGISTERPETRESPONSE']._serialized_start=215
  _globals['_REGISTERPETRESPONSE']._serialized_end=253
  _globals['_SEARCHPETREQUEST']._serialized_start=255
  _globals['_SEARCHPETREQUEST']._serialized_end=331
  _globals['_SEARCHPETRESPONSE']._serialized_start=333
  _globals['_SEARCHPETRESPONSE']._serialized_end=385
  _globals['_PETADOPTIONSERVICE']._serialized_start=388
  _globals['_PETADOPTIONSERVICE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
